Added a loop to monit-start to account for monit process locks
Signed-off-by: Travis Hall <thall@vmware.com>

diff --git a/jobs/bbr-etcd/templates/post-restore-unlock.sh.erb b/jobs/bbr-etcd/templates/post-restore-unlock.sh.erb
--- a/jobs/bbr-etcd/templates/post-restore-unlock.sh.erb
+++ b/jobs/bbr-etcd/templates/post-restore-unlock.sh.erb
@@ -4,21 +4,33 @@ set -euo pipefail
 
 echo "Starting etcd"
 
-/var/vcap/bosh/bin/monit start etcd
-
 TIMEOUT=60
-
 if timeout "$TIMEOUT" /bin/bash <<EOF
   #!/bin/bash
 
-  until /var/vcap/bosh/bin/monit summary | grep etcd | grep running ; do
-    echo "waiting for etcd to start..."
+  until /var/vcap/bosh/bin/monit start etcd; do
+    echo "starting etcd"
     sleep 5
   done
 EOF
 then
-  echo "Etcd has been started and is running"
+  echo "monit has started etcd"
 else
-  echo "Timed out starting etcd after $TIMEOUT seconds"
+  echo "monit was unable to start etcd after $TIMEOUT seconds"
+  exit 1
+fi
+
+if timeout "$TIMEOUT" /bin/bash <<EOF
+  #!/bin/bash
+
+  until /var/vcap/bosh/bin/monit summary | grep etcd | grep "running"; do
+    echo "waiting for etcd daemon to start"
+    sleep 5
+  done
+EOF
+then
+  echo "etcd daemon has started"
+else
+  echo "etcd daemon was unable to start after $TIMEOUT seconds"
   exit 1
 fi
