Refactor the structure of users
[#163786805]

diff --git a/jobs/etcd/templates/bin/post-start.erb b/jobs/etcd/templates/bin/post-start.erb
--- a/jobs/etcd/templates/bin/post-start.erb
+++ b/jobs/etcd/templates/bin/post-start.erb
@@ -35,10 +35,8 @@ setup_users_auth() {
   fi
     <% else %>
   echo "Set up user: $username"
-  permission="<%= user["permission"] %>"
-  path="<%= user["path"] %>"
   role="${username}-role"
-  setup_user_auth "$username" "$password" "$permission" "$path" "$role"
+  setup_user_auth "$username" "$password" "$role"
     <% end %>
   <% end %>
   <% end %>
@@ -52,7 +50,7 @@ setup_users_auth() {
   if [ "$status" -ne 0 ]; then
     enable_auth_duplicate_regex="auth: already enabled"
     if ! [[ $result =~ $enable_auth_duplicate_regex ]]; then
-      echo "Error enable auth: $enable_auth_duplicate_regex"
+      echo "Error enable auth: $result"
       exit 1
     fi
   fi
@@ -74,18 +72,25 @@ setup_user_auth() {
     $etcdctl --username root:$ROOT_PASSWORD role add $role
   fi
 
-  if [[ $permission =~ .*read.* ]]; then
-    read_regex=".*Read:\s+$path.*"
-    if ! [[ $($etcdctl --username root:$ROOT_PASSWORD role get $role) =~ $read_regex ]]; then
-      $etcdctl --username root:$ROOT_PASSWORD role grant $role --read --path "$path" 2>&1
-    fi
+  <%= if user["permissions"]["read"] do |read_paths| %>"
+    <% read_paths.each do |read_path| %>
+  path="<%= read_path %>"
+  read_regex=".*Read:\s+$path.*"
+  if ! [[ $($etcdctl --username root:$ROOT_PASSWORD role get $role) =~ $read_regex ]]; then
+    $etcdctl --username root:$ROOT_PASSWORD role grant $role --read --path "$path"
   fi
-  if [[ $permission =~ .*write.* ]]; then
-    write_regex=".*Write:\s+$path.*"
-    if ! [[ $($etcdctl --username root:$ROOT_PASSWORD role get $role) =~ $write_regex ]]; then
-      $etcdctl --username root:$ROOT_PASSWORD role grant $role --write --path "$path" 2>&1
-    fi
+    <% end %>
+  <% end %>
+
+  <%= if user["permissions"]["write"] do |write_paths| %>"
+    <% write_paths.each do |write_path| %>
+  path="<%= write_path %>"
+  write_regex=".*Write:\s+$path.*"
+  if ! [[ $($etcdctl --username root:$ROOT_PASSWORD role get $role) =~ $write_regex ]]; then
+    $etcdctl --username root:$ROOT_PASSWORD role grant $role --write --path "$path"
   fi
+    <% end %>
+  <% end %>
 
   role_regex="Roles:.*$role"
   if ! [[ "$($etcdctl --username root:$ROOT_PASSWORD user get $username)" =~ $role_regex ]]; then
